name: "Code Formatter"
author: "Sifa Ngari"
description: "Auto formats code on push and pull requests"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The commiter's email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The committer's name
    required: true
    default: ${{ github.actor }}
env:
  GITHUB_EVENT_NAME: ${{ github.event_name }}
  GITHUB_BEFORE: ${{ github.event.before }}
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
  GITHUB_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
